CC=gcc
CFLAGS=-Wall -Wextra -std=gnu99 -fopenmp
DEPS=-lm

q2: question2.c
	$(CC) $(CFLAGS) question2.c -o q2 $(DEPS)

q3: question3.c
	$(CC) $(CFLAGS) question3.c -o q3 $(DEPS)

q4: question_4.c
	$(CC) $(CFLAGS) question_4.c -o q4 $(DEPS) 

q5: question_5.c
	$(CC) $(CFLAGS) question_5.c -o q5 $(DEPS)
